-- MySQL Script generated by MySQL Workbench
-- Fri Jul  5 16:59:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema midiATech
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `midiATech` ;

-- -----------------------------------------------------
-- Schema midiATech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `midiATech` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci ;
USE `midiATech` ;

-- -----------------------------------------------------
-- Table `midiATech`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midiATech`.`users` ;

CREATE TABLE IF NOT EXISTS `midiATech`.`users` (
                                                   `id` INT NOT NULL AUTO_INCREMENT,
                                                   `firstname` VARCHAR(80) NOT NULL,
                                                   `lastname` VARCHAR(80) NOT NULL,
                                                   `birthday` DATE NOT NULL,
                                                   `email` VARCHAR(255) NOT NULL,
                                                   `address` VARCHAR(400) NOT NULL,
                                                   `password` VARCHAR(255) NOT NULL,
                                                   `temporary_password` VARCHAR(255) NULL,
                                                   PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `midiATech`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midiATech`.`categories` ;

CREATE TABLE IF NOT EXISTS `midiATech`.`categories` (
                                                        `id` INT NOT NULL AUTO_INCREMENT,
                                                        `name` VARCHAR(100) NOT NULL,
                                                        PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `midiATech`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midiATech`.`books` ;

CREATE TABLE IF NOT EXISTS `midiATech`.`books` (
                                                   `id` INT NOT NULL AUTO_INCREMENT,
                                                   `title` VARCHAR(255) NOT NULL,
                                                   `picture` VARCHAR(500) NULL,
                                                   `description` LONGTEXT NULL,
                                                   `author` VARCHAR(255) NOT NULL,
                                                   `date` DATE NOT NULL,
                                                   `pages` INT NOT NULL,
                                                   `quantities` INT NOT NULL,
                                                   `id_category` INT NOT NULL,
                                                   PRIMARY KEY (`id`),
                                                   INDEX `fk_books_categories1_idx` (`id_category` ASC) VISIBLE,
                                                   CONSTRAINT `fk_books_categories`
                                                       FOREIGN KEY (`id_category`)
                                                           REFERENCES `midiATech`.`categories` (`id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `midiATech`.`types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midiATech`.`types` ;

CREATE TABLE IF NOT EXISTS `midiATech`.`types` (
                                                   `id` INT NOT NULL AUTO_INCREMENT,
                                                   `name` VARCHAR(100) NOT NULL,
                                                   PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `midiATech`.`videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midiATech`.`videos` ;

CREATE TABLE IF NOT EXISTS `midiATech`.`videos` (
                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                    `title` VARCHAR(255) NOT NULL,
                                                    `picture` VARCHAR(500) NULL,
                                                    `description` LONGTEXT NULL,
                                                    `director` VARCHAR(255) NOT NULL,
                                                    `date` DATE NOT NULL,
                                                    `duration` INT NOT NULL,
                                                    `quantities` INT NOT NULL,
                                                    `id_category` INT NOT NULL,
                                                    `id_types` INT NOT NULL,
                                                    PRIMARY KEY (`id`),
                                                    INDEX `fk_videos_categories1_idx` (`id_category` ASC) VISIBLE,
                                                    INDEX `fk_videos_types1_idx` (`id_types` ASC) VISIBLE,
                                                    CONSTRAINT `fk_videos_categories`
                                                        FOREIGN KEY (`id_category`)
                                                            REFERENCES `midiATech`.`categories` (`id`)
                                                            ON DELETE NO ACTION
                                                            ON UPDATE NO ACTION,
                                                    CONSTRAINT `fk_videos_types`
                                                        FOREIGN KEY (`id_types`)
                                                            REFERENCES `midiATech`.`types` (`id`)
                                                            ON DELETE NO ACTION
                                                            ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `midiATech`.`musics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midiATech`.`musics` ;

CREATE TABLE IF NOT EXISTS `midiATech`.`musics` (
                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                    `title` VARCHAR(255) NOT NULL,
                                                    `picture` VARCHAR(500) NULL,
                                                    `singer` VARCHAR(255) NOT NULL,
                                                    `date` DATE NOT NULL,
                                                    `duration` INT NOT NULL,
                                                    `quantities` INT NOT NULL,
                                                    `id_categories` INT NOT NULL,
                                                    PRIMARY KEY (`id`),
                                                    INDEX `fk_musics_categories1_idx` (`id_categories` ASC) VISIBLE,
                                                    CONSTRAINT `fk_musics_categories`
                                                        FOREIGN KEY (`id_categories`)
                                                            REFERENCES `midiATech`.`categories` (`id`)
                                                            ON DELETE NO ACTION
                                                            ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `midiATech`.`borrowing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midiATech`.`borrowing` ;

CREATE TABLE IF NOT EXISTS `midiATech`.`borrowing` (
                                                       `id_borrowing` INT NOT NULL AUTO_INCREMENT,
                                                       `id_users` INT NOT NULL,
                                                       `id_media` INT NOT NULL,
                                                       `date` DATE NOT NULL,
                                                       PRIMARY KEY (`id_borrowing`, `id_users`, `id_media`),
                                                       INDEX `fk_users_has_books_books1_idx` (`id_media` ASC) VISIBLE,
                                                       INDEX `fk_users_has_books_users_idx` (`id_users` ASC) VISIBLE,
                                                       CONSTRAINT `fk_borrowing_users`
                                                           FOREIGN KEY (`id_users`)
                                                               REFERENCES `midiATech`.`users` (`id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION,
                                                       CONSTRAINT `fk_borrowing_books`
                                                           FOREIGN KEY (`id_media`)
                                                               REFERENCES `midiATech`.`books` (`id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION,
                                                       CONSTRAINT `fk_borrowing_videos`
                                                           FOREIGN KEY (`id_media`)
                                                               REFERENCES `midiATech`.`videos` (`id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION,
                                                       CONSTRAINT `fk_borrowing_musics`
                                                           FOREIGN KEY (`id_media`)
                                                               REFERENCES `midiATech`.`musics` (`id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
