-- MySQL Script generated by MySQL Workbench
-- Fri Jul  5 16:59:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema midiATech
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `midiATech`;

-- -----------------------------------------------------
-- Schema midiATech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `midiATech` DEFAULT CHARACTER
SET
    utf8mb4 COLLATE utf8mb4_0900_as_ci;

USE `midiATech`;

-- -----------------------------------------------------
-- Table `midiATech`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midiATech`.`users`;

CREATE TABLE
    IF NOT EXISTS `midiATech`.`users` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `firstname` VARCHAR(80) NOT NULL,
        `lastname` VARCHAR(80) NOT NULL,
        `birthday` DATE NOT NULL,
        `email` VARCHAR(255) NOT NULL,
        `address` VARCHAR(400) NOT NULL,
        `password` VARCHAR(255) NOT NULL,
        `temporary_password` VARCHAR(255) NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `midiATech`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midiATech`.`categories`;

CREATE TABLE
    IF NOT EXISTS `midiATech`.`categories` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `name` VARCHAR(100) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `midiATech`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midiATech`.`books`;

CREATE TABLE
    IF NOT EXISTS `midiATech`.`books` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `title` VARCHAR(255) NOT NULL,
        `picture` VARCHAR(500) NULL,
        `description` LONGTEXT NULL,
        `author` VARCHAR(255) NOT NULL,
        `date` DATE NOT NULL,
        `pages` INT NOT NULL,
        `quantities` INT NOT NULL,
        `id_category` INT NOT NULL,
        PRIMARY KEY (`id`),
        INDEX `fk_books_categories1_idx` (`id_category` ASC) VISIBLE,
        CONSTRAINT `fk_books_categories` FOREIGN KEY (`id_category`) REFERENCES `midiATech`.`categories` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `midiATech`.`types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midiATech`.`types`;

CREATE TABLE
    IF NOT EXISTS `midiATech`.`types` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `name` VARCHAR(100) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `midiATech`.`videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midiATech`.`videos`;

CREATE TABLE
    IF NOT EXISTS `midiATech`.`videos` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `title` VARCHAR(255) NOT NULL,
        `picture` VARCHAR(500) NULL,
        `description` LONGTEXT NULL,
        `director` VARCHAR(255) NOT NULL,
        `date` DATE NOT NULL,
        `duration` INT NOT NULL,
        `quantities` INT NOT NULL,
        `id_category` INT NOT NULL,
        `id_types` INT NOT NULL,
        PRIMARY KEY (`id`),
        INDEX `fk_videos_categories1_idx` (`id_category` ASC) VISIBLE,
        INDEX `fk_videos_types1_idx` (`id_types` ASC) VISIBLE,
        CONSTRAINT `fk_videos_categories` FOREIGN KEY (`id_category`) REFERENCES `midiATech`.`categories` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_videos_types` FOREIGN KEY (`id_types`) REFERENCES `midiATech`.`types` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `midiATech`.`musics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midiATech`.`musics`;

CREATE TABLE
    IF NOT EXISTS `midiATech`.`musics` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `title` VARCHAR(255) NOT NULL,
        `picture` VARCHAR(500) NULL,
        `singer` VARCHAR(255) NOT NULL,
        `date` DATE NOT NULL,
        `duration` INT NOT NULL,
        `quantities` INT NOT NULL,
        `id_category` INT NOT NULL,
        PRIMARY KEY (`id`),
        INDEX `fk_musics_categories1_idx` (`id_category` ASC) VISIBLE,
        CONSTRAINT `fk_musics_categories` FOREIGN KEY (`id_category`) REFERENCES `midiATech`.`categories` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `midiATech`.`borrowing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midiATech`.`borrowing`;

CREATE TABLE
    IF NOT EXISTS `midiATech`.`borrowing` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `id_users` INT NOT NULL,
        `id_media` INT NOT NULL,
        `media_type` ENUM ('book', 'music', 'video') NOT NULL,
        `date` DATE NOT NULL,
        PRIMARY KEY (`id`),
        INDEX `fk_users_idx` (`id_users` ASC) VISIBLE,
        CONSTRAINT `fk_borrowing_users` FOREIGN KEY (`id_users`) REFERENCES `midiATech`.`users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
    ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `midiATech`.`book_category`
-- -----------------------------------------------------
CREATE TABLE book_category (
    book_id INT NOT NULL,
    category_id INT NOT NULL,
    PRIMARY KEY (book_id, category_id),
    FOREIGN KEY (book_id) REFERENCES books(id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- -----------------------------------------------------
-- Table `midiATech`.`roles`
-- -----------------------------------------------------
CREATE TABLE
    IF NOT EXISTS `midiATech`.`roles` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `name` VARCHAR(50) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE = InnoDB;

INSERT INTO
    types (name)
VALUES
    ('Film'),
    ('Série'),
    ('Jeunesse'),
    ('Documentaire');

INSERT INTO
    categories (name)
VALUES
    ('Video Action'),
    ('Video Animalier'),
    ('Video Animation'),
    ('Video Aventure'),
    ('Video Biographie'),
    ('Video Biopic'),
    ('Video Catastrophe'),
    ('Video Classique'),
    ('Video Comédie'),
    ('Video Comédie dramatique'),
    ('Video Comédie musical'),
    ('Video Comédie romantique'),
    ('Video Court métrage'),
    ('Video Drame'),
    ('Video Fantastique'),
    ('Video Géographique'),
    ('Video Guerre'),
    ('Video Historique'),
    ('Video Horreur'),
    ('Video Humaniste'),
    ('Video Manga'),
    ('Video Médical'),
    ('Video Policier'),
    ('Video Science-fiction'),
    ('Video Thriller'),
    ('Video Western'),
    ('Book Auto-biographie'),
    ('Book Bande-dessinée'),
    ('Book Beaux-livres'),
    ('Book Biographie.'),
    ('Book Conte'),
    ('Book Correspondances'),
    ('Book Essai'),
    ('Book Fable'),
    ('Book Guide pratique'),
    ('Book Livre religieux'),
    ('Book Manga'),
    ('Book Mémoires'),
    ('Book Nouvelle'),
    ('Book Pamphlet'),
    ('Book Poésie en prose'),
    ('Book Poésie en vers'),
    ('Book Recettes de cuisine'),
    ('Book Récits de voyage'),
    ('Book Roman anticipation'),
    ('Book Roman apprentissage'),
    ('Book Roman aventure'),
    ('Book Roman fantasy'),
    ('Book Roman feel-good'),
    ('Book Roman historique'),
    ('Book Roman horreur'),
    ('Book Roman humoristique'),
    ('Book Roman jeunesse'),
    ('Book Roman littérature contemporaine'),
    ('Book Roman mœurs'),
    ('Book Roman noir'),
    ('Book Roman philosophique'),
    ('Book Roman policier'),
    ('Book Roman science-fiction'),
    ('Book Roman sentimental'),
    ('Book Roman thriller'),
    ('Book Scénario'),
    ('Music Afro'),
    ('Music AnimeVerse'),
    ('Music Blues'),
    ('Music Bubble'),
    ('Music Chill'),
    ('Music Classique'),
    ('Music Country'),
    ('Music Culture Queer'),
    ('Music Dance & EDM'),
    ('Music Disco'),
    ('Music Drag Race France'),
    ('Music Films & Séries'),
    ('Music Folk & Acoustique'),
    ('Music Gaming'),
    ('Music Gospel'),
    ('Music Heavy Metal'),
    ('Music Hip Hop'),
    ('Music Indie & Alternative'),
    ('Music Jazz'),
    ('Music K-pop'),
    ('Music Latino'),
    ('Music Lofi'),
    ('Music Metal'),
    ('Music Musique brésilienne'),
    ('Music Musique japonaise'),
    ('Music Musiques du Monde'),
    ('Music Opéra'),
    ('Music Pop'),
    ('Music Punk'),
    ('Music R&B'),
    ('Music Raï'),
    ('Music Rap'),
    ('Music Reggae'),
    ('Music Reggaeton'),
    ('Music Rock'),
    ('Music Rock Alternatif'),
    ('Music Salsa'),
    ('Music Soul & Funk'),
    ('Music Techno'),
    ('Music Trance'),
    ('Music Trap'),
    ('Music Variété française');

INSERT INTO
    `roles` (`name`)
VALUES
    ('admin'),
    ('user');

-- Ajout de la colonne role_id à la table users
ALTER TABLE `midiATech`.`users`
ADD COLUMN `role_id` INT NOT NULL AFTER `temporary_password`,
ADD INDEX `fk_users_roles_idx` (`role_id` ASC),
ADD CONSTRAINT `fk_users_roles` FOREIGN KEY (`role_id`) REFERENCES `midiATech`.`roles` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

INSERT INTO
    videos (
        title,
        picture,
        description,
        director,
        date,
        duration,
        quantities,
        id_category,
        id_types
    )
VALUES
    (
        'Inception',
        'inception.jpg',
        'Un thriller de science-fiction réalisé par Christopher Nolan.',
        'Christopher Nolan',
        '2010-07-16',
        148,
        12,
        24, -- Video Science-fiction
        1
    ),
    (
        'The Godfather',
        'the_godfather.jpg',
        'Un film de crime réalisé par Francis Ford Coppola.',
        'Francis Ford Coppola',
        '1972-03-24',
        175,
        8,
        23, -- Video Policier
        1
    ),
    (
        'The Dark Knight',
        'the_dark_knight.jpg',
        'Un film de super-héros réalisé par Christopher Nolan.',
        'Christopher Nolan',
        '2008-07-18',
        152,
        10,
        1, -- Video Action
        1
    ),
    (
        'Pulp Fiction',
        'pulp_fiction.jpg',
        'Un film néo-noir réalisé par Quentin Tarantino.',
        'Quentin Tarantino',
        '1994-10-14',
        154,
        9,
        9, -- Video Comédie
        1
    ),
    (
        'The Matrix',
        'the_matrix.jpg',
        'Un film de science-fiction réalisé par les Wachowski.',
        'Lana Wachowski, Lilly Wachowski',
        '1999-03-31',
        136,
        15,
        24, -- Video Science-fiction
        1
    ),
    (
        'Fight Club',
        'fight_club.jpg',
        'Un film dramatique réalisé par David Fincher.',
        'David Fincher',
        '1999-10-15',
        139,
        7,
        14, -- Video Drame
        1
    ),
    (
        'Forrest Gump',
        'forrest_gump.jpg',
        'Un film dramatique réalisé par Robert Zemeckis.',
        'Robert Zemeckis',
        '1994-07-06',
        142,
        11,
        14, -- Video Drame
        1
    ),
    (
        'Interstellar',
        'interstellar.jpg',
        'Un film de science-fiction réalisé par Christopher Nolan.',
        'Christopher Nolan',
        '2014-11-07',
        169,
        13,
        24, -- Video Science-fiction
        1
    ),
    (
        'Gladiator',
        'gladiator.jpg',
        'Un film historique réalisé par Ridley Scott.',
        'Ridley Scott',
        '2000-05-05',
        155,
        9,
        18, -- Video Historique
        1
    ),
    (
        'The Shawshank Redemption',
        'shawshank_redemption.jpg',
        'Un film dramatique réalisé par Frank Darabont.',
        'Frank Darabont',
        '1994-09-23',
        142,
        14,
        14, -- Video Drame
        1
    ),
    (
        'The Lord of the Rings: The Fellowship of the Ring',
        'lord_of_the_rings.jpg',
        'Un film de fantasy réalisé par Peter Jackson.',
        'Peter Jackson',
        '2001-12-19',
        178,
        10,
        15, -- Video Fantastique
        1
    ),
    (
        'The Lion King',
        'lion_king.jpg',
        'Un film animation réalisé par Roger Allers et Rob Minkoff.',
        'Roger Allers, Rob Minkoff',
        '1994-06-24',
        88,
        13,
        3, -- Video Animation
        1
    ),
    (
        'Titanic',
        'titanic.jpg',
        'Un film de romance réalisé par James Cameron.',
        'James Cameron',
        '1997-12-19',
        195,
        12,
        12, -- Video Comédie romantique
        1
    ),
    (
        'Jurassic Park',
        'jurassic_park.jpg',
        'Un film de science-fiction réalisé par Steven Spielberg.',
        'Steven Spielberg',
        '1993-06-11',
        127,
        14,
        24, -- Video Science-fiction
        1
    ),
    (
        'The Avengers',
        'the_avengers.jpg',
        'Un film de super-héros réalisé par Joss Whedon.',
        'Joss Whedon',
        '2012-05-04',
        143,
        11,
        1, -- Video Action
        1
    ),
    (
        'Star Wars: Episode IV - A New Hope',
        'star_wars.jpg',
        'Un film de science-fiction réalisé par George Lucas.',
        'George Lucas',
        '1977-05-25',
        121,
        15,
        24, -- Video Science-fiction
        1
    ),
    (
        'The Silence of the Lambs',
        'silence_of_the_lambs.jpg',
        'Un film de thriller réalisé par Jonathan Demme.',
        'Jonathan Demme',
        '1991-02-14',
        118,
        10,
        25, -- Video Thriller
        1
    ),
    (
        'Saving Private Ryan',
        'saving_private_ryan.jpg',
        'Un film de guerre réalisé par Steven Spielberg.',
        'Steven Spielberg',
        '1998-07-24',
        169,
        8,
        17, -- Video Guerre
        1
    ),
    (
        'Schindler \ s List',
        'schindlers_list.jpg',
        'Un film dramatique réalisé par Steven Spielberg.',
        'Steven Spielberg',
        '1993-12-15',
        195,
        9,
        14, -- Video Drame
        1
    ),
    (
        'The Green Mile',
        'the_green_mile.jpg',
        'Un film dramatique réalisé par Frank Darabont.',
        'Frank Darabont',
        '1999-12-10',
        189,
        7,
        14, -- Video Drame
        1
    );

    INSERT INTO
    books (
        title,
        picture,
        description,
        author,
        date,
        pages,
        quantities,
        id_category
    )
VALUES
    (
        'L\'Étranger',
        'letranger.jpg',
        'Un roman de l\'absurde écrit par Albert Camus.',
        'Albert Camus',
        '1942-05-01',
        123,
        10,
        1 -- Roman
    ),
    (
        'Le Petit Prince',
        'le_petit_prince.jpg',
        'Un conte poétique et philosophique écrit par Antoine de Saint-Exupéry.',
        'Antoine de Saint-Exupéry',
        '1943-04-06',
        96,
        15,
        1 -- Roman
    ),
    (
        'Millénium : Les hommes qui n\'aimaient pas les femmes',
        'millenium.jpg',
        'Un roman policier suédois écrit par Stieg Larsson.',
        'Stieg Larsson',
        '2005-08-09',
        465,
        20,
        2 -- Policier
    ),
    (
        'Dune',
        'dune.jpg',
        'Un roman de science-fiction écrit par Frank Herbert.',
        'Frank Herbert',
        '1965-08-01',
        412,
        8,
        3 -- Science-fiction
    ),
    (
        'Harry Potter à l\'école des sorciers',
        'harry_potter.jpg',
        'Un roman fantastique écrit par J.K. Rowling.',
        'J.K. Rowling',
        '1997-06-26',
        309,
        12,
        4 -- Fantastique
    ),
    (
        'Sapiens : Une brève histoire de l\'humanité',
        'sapiens.jpg',
        'Un essai explorant l\'histoire de l\'espèce humaine.',
        'Yuval Noah Harari',
        '2011-06-04',
        498,
        10,
        33 -- Essai
    ),
    (
        'Les Misérables',
        'les_miserables.jpg',
        'Un roman historique écrit par Victor Hugo.',
        'Victor Hugo',
        '1862-01-14',
        1488,
        11,
        50 -- Roman historique
    ),
    (
        '1984',
        '1984.jpg',
        'Un roman de science-fiction dystopique écrit par George Orwell.',
        'George Orwell',
        '1949-06-08',
        328,
        9,
        59 -- Roman science-fiction
    ),
    (
        'Le Nom de la rose',
        'le_nom_de_la_rose.jpg',
        'Un roman policier historique écrit par Umberto Eco.',
        'Umberto Eco',
        '1980-04-01',
        500,
        14,
        58 -- Roman policier
    ),
    (
        'La Quête d\'Ewilan : D\'un monde à l\'autre',
        'ewilan.jpg',
        'Un roman de fantasy jeunesse écrit par Pierre Bottero.',
        'Pierre Bottero',
        '2003-10-01',
        320,
        8,
        53 -- Roman jeunesse
    ),
    (
        'La Roue du Temps : L\'Œil du Monde',
        'la_roue_du_temps.jpg',
        'Un roman de fantasy écrit par Robert Jordan.',
        'Robert Jordan',
        '1990-01-15',
        688,
        10,
        48 -- Roman fantasy
    ),
    (
        'Outlander : Le Chardon et le Tartan',
        'outlander.jpg',
        'Un roman de romance historique écrit par Diana Gabaldon.',
        'Diana Gabaldon',
        '1991-06-01',
        850,
        12,
        60 -- Roman sentimental
    ),
    (
        'Le Seigneur des Anneaux : La Communauté de l\'Anneau',
        'le_seigneur_des_anneaux.jpg',
        'Un roman de fantasy écrit par J.R.R. Tolkien.',
        'J.R.R. Tolkien',
        '1954-07-29',
        479,
        15,
        48 -- Roman fantasy
    ),
    (
        'Pride and Prejudice',
        'pride_and_prejudice.jpg',
        'Un roman de romance écrit par Jane Austen.',
        'Jane Austen',
        '1813-01-28',
        432,
        11,
        60 -- Roman sentimental
    ),
    (
        'La Passe-Miroir : Les Fiancés de l\'hiver',
        'la_passe_miroir.jpg',
        'Un roman de fantasy jeunesse écrit par Christelle Dabos.',
        'Christelle Dabos',
        '2013-06-06',
        528,
        9,
        53 -- Roman jeunesse
    ),
    (
        'Le Labyrinthe',
        'le_labyrinthe.jpg',
        'Un roman dystopique jeunesse écrit par James Dashner.',
        'James Dashner',
        '2009-10-06',
        375,
        8,
        53 -- Roman jeunesse
    ),
    (
        'Les Chroniques de Narnia : Le Lion, la Sorcière blanche et l\'Armoire magique',
        'narnia.jpg',
        'Un roman de fantasy jeunesse écrit par C.S. Lewis.',
        'C.S. Lewis',
        '1950-10-16',
        208,
        14,
        53 -- Roman jeunesse
    ),
    (
        'Twilight : Fascination',
        'twilight.jpg',
        'Un roman de fantasy romantique écrit par Stephenie Meyer.',
        'Stephenie Meyer',
        '2005-10-05',
        498,
        10,
        60 -- Roman sentimental
    ),
    (
        'Roméo et Juliette',
        'romeo_et_juliette.jpg',
        'Un roman de romance tragique écrit par William Shakespeare.',
        'William Shakespeare',
        '1597-01-01',
        128,
        12,
        60 -- Roman sentimental
    ),
    (
        'Le Clan des Otori : Le Silence du Rossignol',
        'le_clan_des_otori.jpg',
        'Un roman de fantasy historique écrit par Lian Hearn.',
        'Lian Hearn',
        '2002-04-03',
        287,
        7,
        50 -- Roman historique
    ),
    (
        'Hunger Games',
        'hunger_games.jpg',
        'Un roman dystopique jeunesse écrit par Suzanne Collins.',
        'Suzanne Collins',
        '2008-09-14',
        374,
        13,
        53 -- Roman jeunesse
    ),
    (
        'Eragon',
        'eragon.jpg',
        'Un roman de fantasy jeunesse écrit par Christopher Paolini.',
        'Christopher Paolini',
        '2002-08-26',
        503,
        12,
        53 -- Roman jeunesse
    ),
    (
        'Orgueil et Préjugés et Zombies',
        'orgueil_prejuges_zombies.jpg',
        'Un roman de fantasy parodique écrit par Seth Grahame-Smith.',
        'Seth Grahame-Smith',
        '2009-04-01',
        320,
        9,
        48 -- Roman fantasy
    ),
    (
        'La Sélection',
        'la_selection.jpg',
        'Un roman de romance dystopique écrit par Kiera Cass.',
        'Kiera Cass',
        '2012-04-24',
        336,
        10,
        60 -- Roman sentimental
    ),
    (
        'Les Chevaliers d\'Émeraude',
        'chevaliers_emeraude.jpg',
        'Un roman de fantasy jeunesse écrit par Anne Robillard.',
        'Anne Robillard',
        '2002-10-01',
        444,
        12,
        53 -- Roman jeunesse
    ),
    (
        'Nos étoiles contraires',
        'nos_etoiles_contraires.jpg',
        'Un roman de romance jeunesse écrit par John Green.',
        'John Green',
        '2012-01-10',
        336,
        11,
        60 -- Roman sentimental
    ),
    (
        'Percy Jackson : Le Voleur de foudre',
        'percy_jackson.jpg',
        'Un roman de fantasy jeunesse écrit par Rick Riordan.',
        'Rick Riordan',
        '2005-06-28',
        377,
        15,
        53 -- Roman jeunesse
    ),
    (
        'Le Hobbit',
        'le_hobbit.jpg',
        'Un roman de fantasy écrit par J.R.R. Tolkien.',
        'J.R.R. Tolkien',
        '1937-09-21',
        310,
        14,
        48 -- Roman fantasy
    ),
    (
        'La Belle et la Bête',
        'la_belle_et_la_bete.jpg',
        'Un conte de fées écrit par Jeanne-Marie Leprince de Beaumont.',
        'Jeanne-Marie Leprince de Beaumont',
        '1756-01-01',
        120,
        12,
        60 -- Roman sentimental
    );
